# Lab 3: Box average

Name: Jacob Yeung
Course + section: CS 121 #19990
Date: Mar 02 2026
Assignment title:
## Lab: 2D Moving Average (Box Blur) with NumPy ndarrays

In the last lab you computed a moving/rolling average on a 1D list. In this lab, you’ll extend that idea to 2D space using NumPy ndarrays. This is the same core idea behind a blur effects, they are basically a weighted average applied to a pixel based on the value of the pixels around it. In this lab you will be moving an array or a "box" from the start into the end of the list. One way of seeing this is a box moving around the 2d array from the beginning of the list till the end.

This idea will become more relevant when we get to machine learning and you start looking into Convolution for Image data.

#### Write a pure function that takes only a 2D NumPy array and returns a new 2D array that contains the 3×3 moving average (box blur) for every valid center cell.
** Include your function box_blur_3x3(input_array) (one parameter only).

In [1]:
import random

# NumPy installed and imported as import numpy as np
import numpy as np

# Use NumPy features: .shape, slicing, and .mean().
def box_blur_3x3(inputArray):
    # Read input dimensions: n, m = input_array.shape
    n, m = input_array.shape
    # Create an output array of zeros with shape (n-2, m-2)
    outputArray = np.zeros((n - 2, m - 2))

    for i in range(1, n - 1):
        for j in range(1, m - 1):
            # Comfort with 2D indexing and slicing: A[r0:r1, c0:c1]
            # For each valid center (exclude borders), slice a 3×3 window
            window = input_array[i-1:i+2, j-1:j+2]
            # Compute the window average using NumPy mean()
            # Store the result in the output array
            outputArray[i-1, j-1] = window.mean()

# Create and return a NumPy output array with shape (n − 2, m − 2).
    return outputArray


In [16]:
import numpy as np

input_array = np.array([[3, 5, 6, 7,1],
                        [2,3,4,9,4],
                        [4,1,5,1,2],
                        [2,8,4,7,3],
                        [6,8,9,1,2]])


print("## Test 01: One small, readable array (ex: 5×5 with known values)")
np.set_printoptions(linewidth = 2000, precision=1, suppress=True)
print("Input Array:\n", input_array)
print("Blurred Array:\n", blurred := box_blur_3x3(input_array))


## Test 01: One small, readable array (ex: 5×5 with known values)
Input Array:
 [[3 5 6 7 1]
 [2 3 4 9 4]
 [4 1 5 1 2]
 [2 8 4 7 3]
 [6 8 9 1 2]]
Blurred Array:
 [[3.7 4.6 4.3]
 [3.7 4.7 4.3]
 [5.2 4.9 3.8]]


In [21]:
import numpy as np
import random as rand
MAX_NUMBER = 100
matrixSize = rand.randint(50, MAX_NUMBER)

print("## Test 02: One larger random array (ex: 50×50 or bigger)")
print(f"create {matrixSize} x {matrixSize} random matrix: (from 0 to {MAX_NUMBER})")
input_array = np.random.randint(0,MAX_NUMBER+1,size=(matrixSize, matrixSize))

np.set_printoptions(threshold=np.inf, linewidth = 2000, precision=1, suppress=True) # Set line width and precision for better readability
print("Input Array:\n", input_array)
print("Blurred Array:\n", blurred := box_blur_3x3(input_array))
# print("Formatted Blurred Array:\n", np.array([[f"{x:.2f}" for x in row] for row in blurred]))


## Test 02: One larger random array (ex: 50×50 or bigger)
create 60 x 60 random matrix: (from 0 to 100)
Input Array:
 [[ 94  16  22  88  29  85  19  58  59  27  13  60  89  54  56  70  30  64  82  12  91  28   6  16  40  67  13   0  24  82  34  36  73  88  51  68  22  62  71   3  11  56  25  80  54  84  24   2  45  11  12  26  11  90  81  13  70  88  25  51]
 [ 68   6  90  88  15  91  33  53  53  44  35  70  55  57  38  14   0  45  43  46  75  76  50   4  15  38  55  65  91  67  92  42  20  60  18  64  89  93  26  80  58  28  14   0   4  36  47  40  28  24  80   4  42  96  37  70   4  53  45  75]
 [ 81  25  55  93  48  50  84  13   5  78  13  98  69  45  55  17  56  71  81  53  64  46  78  49  88  78  22  67  87  65  93  65  29 100  68  23  13  90  82  25   6  43  38  80  79  18  29  35  70   2  38  79  56  26  57   0  19  70  18  37]
 [ 47  22  53  27  22  45  86  22  68  67  14  27  65  35  70   3  20  37  44  20  64  93  64  49  19   5  78  29  43  80  11  67  48  91   2  18  14  51